# Generated by Django 4.1.2 on 2023-02-25 06:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prizes_text', models.CharField(max_length=100)),
                ('points_required', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(null=True, upload_to='prize_images/')),
                ('pub_date', models.DateTimeField(verbose_name='date added')),
                ('start_date', models.DateField(default=datetime.datetime(2023, 2, 25, 6, 41, 34, 423492, tzinfo=datetime.timezone.utc))),
                ('start_time', models.TimeField(default=datetime.datetime(2023, 2, 25, 6, 41, 34, 423492, tzinfo=datetime.timezone.utc))),
                ('end_date', models.DateField(default=datetime.datetime(2023, 2, 26, 6, 41, 34, 423492, tzinfo=datetime.timezone.utc))),
                ('end_time', models.TimeField(default=datetime.datetime(2023, 2, 26, 6, 41, 34, 423492, tzinfo=datetime.timezone.utc))),
                ('visibility', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 26, 6, 41, 34, 416970, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2023, 2, 26, 6, 41, 34, 416970, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(null=True, upload_to='event_images/'),
        ),
        migrations.AddField(
            model_name='event',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 25, 6, 41, 34, 416970, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2023, 2, 25, 6, 41, 34, 416970, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='event',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(verbose_name='date added'),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
    ]
