# Generated by Django 4.1.2 on 2023-02-25 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_alter_event_pub_date_alter_prize_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 2, 25, 20, 11, 38, 305675, tzinfo=datetime.timezone.utc), verbose_name='date added'),
        ),
        migrations.AlterField(
            model_name='prize',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 26, 20, 11, 38, 305675, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='prize',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2023, 2, 26, 20, 11, 38, 305675, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='prize',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 2, 25, 20, 11, 38, 305675, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='prize',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2023, 2, 25, 20, 11, 38, 305675, tzinfo=datetime.timezone.utc)),
        ),
    ]
