# Generated by Django 4.1.2 on 2023-02-26 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20230225_1742'),
        ('events', '0018_alter_event_pub_date_alter_prize_end_date_and_more'),
    ]

    operations = [
    ]
