# Generated by Django 3.2.6 on 2023-02-27 02:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize_name', models.CharField(max_length=100)),
                ('coins_required', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('date_received', models.DateField(default=datetime.datetime(2023, 2, 27, 2, 5, 56, 297768, tzinfo=utc))),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/img/prize_images/')),
                ('can_be_redeemed', models.BooleanField(default=False)),
                ('visibility', models.BooleanField(default=False)),
            ],
        ),
    ]
