# Generated by Django 3.2.6 on 2023-02-28 02:35

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('prizes', '0002_remove_prize_date_received'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prize',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
